# Generated by Django 3.0.9 on 2020-08-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_auto_20200804_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbm_num',
            new_name='isbn_num',
        ),
    ]
